title: Mohiuddin Amanulla Chishty
logo: /assets/img/Profile_pic.png
#description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
another_url: https://www.linkedin.com/in/mohiuddin-amanulla-c-918717b2/

  
